
export const menus = [
    {
        "id": 1,
        "parentId": 0,
        "name": "资料",
        "icon": "",
        "url": null,
        "path": "/dashboard",
        "sort": 1,
        "type": 1,
        "hidden": false,
        "pathMethod": null,
        "children": [
            {
                "id": 7,
                "parentId": 1,
                "name": "公司信息",
                "icon": null,
                "url": null,
                "path": "/list/search",
                "sort": 1,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 8,
                "parentId": 1,
                "name": "员工信息",
                "icon": null,
                "url": null,
                "path": "/basedata/person",
                "sort": 2,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 9,
                "parentId": 1,
                "name": "机台资料",
                "icon": null,
                "url": null,
                "path": "/dashboard9",
                "sort": 3,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 10,
                "parentId": 1,
                "name": "查布记录",
                "icon": null,
                "url": null,
                "path": "/dashboard10",
                "sort": 4,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 11,
                "parentId": 1,
                "name": "纱支",
                "icon": null,
                "url": null,
                "path": "/dashboard11",
                "sort": 5,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 12,
                "parentId": 1,
                "name": "客户",
                "icon": null,
                "url": null,
                "path": "/dashboard12",
                "sort": 6,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 13,
                "parentId": 1,
                "name": "供应商",
                "icon": null,
                "url": null,
                "path": "/dashboard13",
                "sort": 7,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 14,
                "parentId": 1,
                "name": "参数设置",
                "icon": null,
                "url": null,
                "path": "/dashboard14",
                "sort": 8,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            }
        ],
        "roleId": null,
        "menuIds": null
    },
    {
        "id": 2,
        "parentId": 0,
        "name": "生产",
        "icon": null,
        "url": null,
        "path": "/dashboard2",
        "sort": 2,
        "type": 1,
        "hidden": false,
        "pathMethod": null,
        "children": [
            {
                "id": 15,
                "parentId": 2,
                "name": "订单管理",
                "icon": null,
                "url": null,
                "path": "/dashboard15",
                "sort": 1,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 16,
                "parentId": 2,
                "name": "生产进度",
                "icon": null,
                "url": null,
                "path": "/dashboard16",
                "sort": 2,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 17,
                "parentId": 2,
                "name": "查布明细",
                "icon": null,
                "url": null,
                "path": "/dashboard17",
                "sort": 3,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 18,
                "parentId": 2,
                "name": "查布工资",
                "icon": null,
                "url": null,
                "path": "/dashboard18",
                "sort": 4,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            }
        ],
        "roleId": null,
        "menuIds": null
    },
    {
        "id": 3,
        "parentId": 0,
        "name": "坯布库存",
        "icon": null,
        "url": null,
        "path": "/dashboard3",
        "sort": 3,
        "type": 1,
        "hidden": false,
        "pathMethod": null,
        "children": [
            {
                "id": 19,
                "parentId": 3,
                "name": "坯布出货",
                "icon": null,
                "url": null,
                "path": "/dashboard19",
                "sort": 1,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 20,
                "parentId": 3,
                "name": "出货明细",
                "icon": null,
                "url": null,
                "path": "/dashboard20",
                "sort": 2,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 21,
                "parentId": 3,
                "name": "库存",
                "icon": null,
                "url": null,
                "path": "/dashboard21",
                "sort": 3,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 22,
                "parentId": 3,
                "name": "入库报表",
                "icon": null,
                "url": null,
                "path": "/dashboard22",
                "sort": 4,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            }
        ],
        "roleId": null,
        "menuIds": null
    },
    {
        "id": 4,
        "parentId": 0,
        "name": "纱线库存",
        "icon": null,
        "url": null,
        "path": "/dashboard4",
        "sort": 4,
        "type": 1,
        "hidden": false,
        "pathMethod": null,
        "children": [
            {
                "id": 23,
                "parentId": 4,
                "name": "收纱入库",
                "icon": null,
                "url": null,
                "path": "/dashboard23",
                "sort": 1,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 24,
                "parentId": 4,
                "name": "退纱出库",
                "icon": null,
                "url": null,
                "path": "/dashboard24",
                "sort": 2,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 25,
                "parentId": 4,
                "name": "出入明细",
                "icon": null,
                "url": null,
                "path": "/dashboard25",
                "sort": 3,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 26,
                "parentId": 4,
                "name": "库存",
                "icon": null,
                "url": null,
                "path": "/dashboard26",
                "sort": 4,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            }
        ],
        "roleId": null,
        "menuIds": null
    },
    {
        "id": 5,
        "parentId": 0,
        "name": "报表",
        "icon": null,
        "url": null,
        "path": "/dashboard5",
        "sort": 5,
        "type": 1,
        "hidden": false,
        "pathMethod": null,
        "children": [
            {
                "id": 27,
                "parentId": 5,
                "name": "生产报表",
                "icon": null,
                "url": null,
                "path": "/dashboard27",
                "sort": 1,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 28,
                "parentId": 5,
                "name": "行为分析",
                "icon": null,
                "url": null,
                "path": "/dashboard28",
                "sort": 2,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 29,
                "parentId": 5,
                "name": "性能分析",
                "icon": null,
                "url": null,
                "path": "/dashboard29",
                "sort": 3,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            }
        ],
        "roleId": null,
        "menuIds": null
    },
    {
        "id": 6,
        "parentId": 0,
        "name": "系统",
        "icon": null,
        "url": null,
        "path": "/dashboard6",
        "sort": 6,
        "type": 1,
        "hidden": false,
        "pathMethod": null,
        "children": [
            {
                "id": 30,
                "parentId": 6,
                "name": "菜单管理",
                "icon": null,
                "url": null,
                "path": "/dashboard30",
                "sort": 1,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 31,
                "parentId": 6,
                "name": "用户管理",
                "icon": null,
                "url": null,
                "path": "/dashboard31",
                "sort": 2,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 32,
                "parentId": 6,
                "name": "权限配置",
                "icon": null,
                "url": null,
                "path": "/dashboard32",
                "sort": 3,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 33,
                "parentId": 6,
                "name": "操作动态",
                "icon": null,
                "url": null,
                "path": "/dashboard33",
                "sort": 4,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            },
            {
                "id": 34,
                "parentId": 6,
                "name": "系统通知",
                "icon": null,
                "url": null,
                "path": "/dashboard34",
                "sort": 5,
                "type": 1,
                "hidden": false,
                "pathMethod": null,
                "children": null,
                "roleId": null,
                "menuIds": null
            }
        ],
        "roleId": null,
        "menuIds": null
    }
]